load("@com_github_grpc_grpc//bazel:grpc_build_system.bzl", "grpc_proto_library")

grpc_proto_library(
    name = "two_phase_commit_adapter",
    srcs = ["two_phase_commit_adapter.proto"],
    well_known_protos = True,
)
