package(default_visibility = ["//visibility:public"])

cc_library(
    name = "grpc_utils",
    srcs = [
        "grpc_utils.cc",
        "grpc_utils.h",
    ],
    hdrs = ["grpc_utils.h"],
    deps = [
        "@com_github_grpc_grpc//:grpc++",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/strings",
    ],
)
